/**
 * Full Name: Thomas Lawrence
 *
 * Student ID: 041120273
 *
 * Course: CST3104
 *
 * Term: Fall 2024
 *
 * Assignment: Team Project
 *
 * Date: November 24 2024
 */

package com.cst3104.project.marvel;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Represents a user and their score, stored in the `UserInfo` table of the database.
 */
@Entity
public class UserInfo {

    /**
     * The score achieved by the user.
     */
    @ColumnInfo(name = "Score")
    protected int score;

    /**
     * The timestamp of when the score was recorded.
     */
    @ColumnInfo(name = "TimeStamp")
    protected String timestamp;

    /**
     * The name of the user.
     */
    @ColumnInfo(name = "UserName")
    protected String userName;

    /**
     * The primary key for the `UserInfo` table. Auto-generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    public int id;

    /**
     * Constructs a new `UserInfo` object with the specified score and username.
     * Automatically sets the current timestamp.
     *
     * @param score    The user's score.
     * @param userName The user's name.
     */
    public UserInfo(int score, String userName) {
        this.score = score;
        this.userName = userName;
        this.timestamp = getCurrentTime();  // Automatically set the current time
    }

    /**
     * Generates the current timestamp in the format `yyyy-MM-dd HH:mm:ss`.
     *
     * @return A string representing the current timestamp.
     */
    private String getCurrentTime() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        return LocalDateTime.now().format(formatter);
    }

    /**
     * Gets the ID of the user.
     *
     * @return The user's ID.
     */
    public int getId() {
        return id;
    }
}
